# Generated by ariadne-codegen
# Source: dagster_rest_resources/queries

from typing import TYPE_CHECKING, Any, Dict

from .base_client import BaseClient

if TYPE_CHECKING:
    from .get_organization_settings import GetOrganizationSettings
    from .input_types import OrganizationSettingsInput
    from .update_organization_settings import UpdateOrganizationSettings


def gql(q: str) -> str:
    return q


class Client(BaseClient):
    def get_organization_settings(self, **kwargs: Any) -> "GetOrganizationSettings":
        from .get_organization_settings import GetOrganizationSettings

        query = gql(
            """
            query GetOrganizationSettings {
              organizationSettings {
                settings
              }
            }
            """
        )
        variables: Dict[str, object] = {}
        response = self.execute(
            query=query,
            operation_name="GetOrganizationSettings",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return GetOrganizationSettings.model_validate(data)

    def update_organization_settings(
        self, organization_settings: "OrganizationSettingsInput", **kwargs: Any
    ) -> "UpdateOrganizationSettings":
        from .update_organization_settings import UpdateOrganizationSettings

        query = gql(
            """
            mutation UpdateOrganizationSettings($organizationSettings: OrganizationSettingsInput!) {
              setOrganizationSettings(organizationSettings: $organizationSettings) {
                __typename
                ... on OrganizationSettings {
                  settings
                }
                ... on UnauthorizedError {
                  message
                }
                ... on PythonError {
                  message
                }
              }
            }
            """
        )
        variables: Dict[str, object] = {"organizationSettings": organization_settings}
        response = self.execute(
            query=query,
            operation_name="UpdateOrganizationSettings",
            variables=variables,
            **kwargs
        )
        data = self.get_data(response)
        return UpdateOrganizationSettings.model_validate(data)
